/*
Automatically generated header. Use '../tools/cli_help.hpp.py' to modify/regenerate.
*/

static const char cli_help[] = 
	"usage: unalix [-h] [-v] -u URL\n"
	"              [-s] [-l]\n"
	"              [--strict-errors]\n"
	"              [--skip-blocked]\n"
	"              [--ignore-rules]\n"
	"              [--ignore-raw]\n"
	"              [--ignore-referral]\n"
	"              [--ignore-exceptions]\n"
	"              [--ignore-redirections]\n"
	"              [--timeout TIMEOUT]\n"
	"              [--max-redirs MAX_REDIRS]\n"
	"              [--user-agent USER_AGENT]\n"
	"              [--dns-server DNS_SERVER]\n"
	"              [--proxy PROXY]\n"
	"              [--proxy-user PROXY_USER]\n"
	"              [--proxy-pass PROXY_PASS]\n"
	"\n"
	"options:\n"
	"  -h, --help  show this help\n"
	"              message and exit\n"
	"  -v, --version\n"
	"              show version number\n"
	"              and exit\n"
	"  -u URL, --url URL\n"
	"              Specify a URL to\n"
	"              remove tracking\n"
	"              fields from\n"
	"  -s, --unshort\n"
	"              Unshort URLs (HTTP\n"
	"              requests will be\n"
	"              made)\n"
	"  -l, --launch-with-browser\n"
	"              Open URLs with\n"
	"              user's default\n"
	"              browser\n"
	"  --strict-errors\n"
	"              Fail and exit on the\n"
	"              first detected error\n"
	"\n"
	"URL filtering:\n"
	"  --skip-blocked\n"
	"              Ignore patterns when\n"
	"              <completeProvider>\n"
	"              is true\n"
	"  --ignore-rules\n"
	"              Ignore <rules>\n"
	"              patterns\n"
	"  --ignore-raw\n"
	"              Ignore <rawRules>\n"
	"              patterns\n"
	"  --ignore-referral\n"
	"              Ignore\n"
	"              <referralMarketing>\n"
	"              patterns\n"
	"  --ignore-exceptions\n"
	"              Ignore <exceptions>\n"
	"              patterns\n"
	"  --ignore-redirections\n"
	"              Ignore\n"
	"              <redirections>\n"
	"              patterns\n"
	"\n"
	"HTTP options:\n"
	"  --timeout TIMEOUT\n"
	"              Maximum time in\n"
	"              seconds that you\n"
	"              allow unalix's\n"
	"              socket operations to\n"
	"              take\n"
	"  --max-redirs MAX_REDIRS\n"
	"              Set maximum number\n"
	"              of redirections to\n"
	"              follow\n"
	"  --user-agent USER_AGENT\n"
	"              Specify the User-\n"
	"              Agent string to send\n"
	"              to the HTTP server\n"
	"\n"
	"DNS options:\n"
	"  --dns-server DNS_SERVER\n"
	"              Set the DNS server\n"
	"              to be used instead\n"
	"              of the system\n"
	"              default\n"
	"\n"
	"Proxy options:\n"
	"  --proxy PROXY\n"
	"              Use the specified\n"
	"              proxy\n"
	"  --proxy-user PROXY_USER\n"
	"              Specify the user\n"
	"              name to use for\n"
	"              proxy authentication\n"
	"  --proxy-pass PROXY_PASS\n"
	"              Specify the password\n"
	"              to use for proxy\n"
	"              authentication\n"
	"\n"
	"Note, options that take an\n"
	"argument require a equal sign.\n"
	"E.g. -u=URL\n";
