#include "errors.h"

const char* strerrorcode(const int code) {
	/*
	switch (code) {
		case UNALIXERR_SUCCESS:
			return "UNALIXERR_SUCCESS";
		case UNALIXERR_CANNOT_OPEN_FILE:
			return "UNALIXERR_CANNOT_OPEN_FILE";
		case UNALIXERR_JSON_CANNOT_PARSE:
			return "UNALIXERR_JSON_CANNOT_PARSE";
		case UNALIXERR_JSON_MISSING_REQUIRED_KEY:
			return "UNALIXERR_JSON_MISSING_REQUIRED_KEY";
		case UNALIXERR_JSON_NON_MATCHING_TYPE:
			return "UNALIXERR_JSON_NON_MATCHING_TYPE";
		case UNALIXERR_PCRE2_COMPILE_PATTERN_FAILED:
			return "UNALIXERR_PCRE2_COMPILE_PATTERN_FAILED";
		case UNALIXERR_URI_MISSING_SCHEME:
			return "UNALIXERR_URI_MISSING_SCHEME";
		case UNALIXERR_URI_INVALID_SCHEME:
			return "UNALIXERR_URI_INVALID_SCHEME";
		case UNALIXERR_URI_EMPTY_SCHEME:
			return "UNALIXERR_URI_EMPTY_SCHEME";
		case UNALIXERR_URI_HOSTNAME_TOO_LONG:
			return "UNALIXERR_URI_HOSTNAME_TOO_LONG";
		case UNALIXERR_URI_HOSTNAME_TOO_SHORT:
			return "UNALIXERR_URI_HOSTNAME_TOO_SHORT";
		case UNALIXERR_URI_LABEL_TOO_LONG:
			return "UNALIXERR_URI_LABEL_TOO_LONG";
		case UNALIXERR_URI_LABEL_EMPTY:
			return "UNALIXERR_URI_LABEL_EMPTY";
		case UNALIXERR_URI_LABEL_CONTAINS_UPPERCASE:
			return "UNALIXERR_URI_LABEL_CONTAINS_UPPERCASE";
		case UNALIXERR_URI_LABEL_CONTAINS_INVALID_CHARACTER:
			return "UNALIXERR_URI_LABEL_CONTAINS_INVALID_CHARACTER";
		case UNALIXERR_URI_LABEL_CONNOT_STARTS_WITH_HYPHEN:
			return "UNALIXERR_URI_LABEL_CONNOT_STARTS_WITH_HYPHEN";
		case UNALIXERR_URI_LABEL_CONNOT_ENDS_WITH_HYPHEN:
			return "UNALIXERR_URI_LABEL_CONNOT_ENDS_WITH_HYPHEN";
		case UNALIXERR_URI_PORT_TOO_SHORT:
			return "UNALIXERR_URI_PORT_TOO_SHORT";
		case UNALIXERR_URI_PORT_TOO_LONG:
			return "UNALIXERR_URI_PORT_TOO_LONG";
		case UNALIXERR_URI_PORT_CONTAINS_INVALID_CHARACTER:
			return "UNALIXERR_URI_PORT_CONTAINS_INVALID_CHARACTER";
		case UNALIXERR_URI_PORT_INVALID_NUMBER:
			return "UNALIXERR_URI_PORT_INVALID_NUMBER";
		case UNALIXERR_URI_HOSTNAME_MISSING_CLOSING_BRACKET:
			return "UNALIXERR_URI_HOSTNAME_MISSING_CLOSING_BRACKET";
		case UNALIXERR_URI_IPV6_ADDRESS_TOO_SHORT:
			return "UNALIXERR_URI_IPV6_ADDRESS_TOO_SHORT";
		case UNALIXERR_URI_IPV6_ADDRESS_TOO_LONG:
			return "UNALIXERR_URI_IPV6_ADDRESS_TOO_LONG";
		case UNALIXERR_URI_IPV6_ADDRESS_INVALID:
			return "UNALIXERR_URI_IPV6_ADDRESS_INVALID";
		case UNALIXERR_RULESETS_EMPTY:
			return "UNALIXERR_RULESETS_EMPTY";
		case UNALIXERR_DNS_BUFFER_SIZE_TOO_SMALL:
			return "UNALIXERR_DNS_BUFFER_SIZE_TOO_SMALL";
		case UNALIXERR_DNS_BUFFER_SIZE_TOO_HIGH:
			return "UNALIXERR_DNS_BUFFER_SIZE_TOO_HIGH";
		default:
			return "UNALIXERR_UNKNOWN";
	}
	*/
}
